/****** Object:  Database [cm-db]    Script Date: 29/07/2020 16:24:15 ******/
CREATE DATABASE [cm-db]  (EDITION = 'Standard', SERVICE_OBJECTIVE = 'S0', MAXSIZE = 50 GB) WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [cm-db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [cm-db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [cm-db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [cm-db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [cm-db] SET ARITHABORT OFF 
GO

ALTER DATABASE [cm-db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [cm-db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [cm-db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [cm-db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [cm-db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [cm-db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [cm-db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [cm-db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [cm-db] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [cm-db] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [cm-db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [cm-db] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [cm-db] SET  MULTI_USER 
GO

ALTER DATABASE [cm-db] SET ENCRYPTION ON
GO

ALTER DATABASE [cm-db] SET QUERY_STORE = ON
GO

ALTER DATABASE [cm-db] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 100, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO)
GO

/*** The scripts of database scoped configurations in Azure should be executed inside the target database connection. ***/
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET ACCELERATED_PLAN_FORCING = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET ASYNC_STATS_UPDATE_WAIT_AT_LOW_PRIORITY = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ADAPTIVE_JOINS = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET DW_COMPATIBILITY_LEVEL = 0;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_ONLINE = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET ELEVATE_RESUMABLE = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET EXEC_QUERY_STATS_FOR_SCALAR_FUNCTIONS = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET GLOBAL_TEMPORARY_TABLE_AUTO_DROP = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET ISOLATE_SECURITY_POLICY_CARDINALITY = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET LAST_QUERY_PLAN_STATS = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET LIGHTWEIGHT_QUERY_PROFILING = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET OPTIMIZE_FOR_AD_HOC_WORKLOADS = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET PAUSED_RESUMABLE_INDEX_ABORT_DURATION_MINUTES = 1440;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET VERBOSE_TRUNCATION_WARNINGS = ON;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET XTP_PROCEDURE_EXECUTION_STATISTICS = OFF;
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET XTP_QUERY_EXECUTION_STATISTICS = OFF;
GO

ALTER DATABASE [cm-db] SET  READ_WRITE 
GO

